#!/usr/bin/env python

# Create a json file from CMSDIST config.map file.

from urllib2 import urlopen
import json

CONFIG_MAP_URL = "https://raw.githubusercontent.com/cms-sw/cmsdist/HEAD/config.map"

if __name__ == "__main__":
  f = urlopen("https://raw.githubusercontent.com/cms-sw/cmsdist/HEAD/config.map")
  lines = f.read()
  entries = [p.strip(";").split(";") for p in lines.split()]
  pairs = [dict([i.split("=") for i in e]) for e in entries]
  print json.dumps(pairs, sort_keys=True, indent=2, separators=(',', ': '))
