var categories = {
  0 : "alca",
  1 : "analysis",
  2 : "core",
  3 : "daq",
  4 : "db",
  5 : "dqm",
  6 : "externals",
  7 : "fastsim",
  8 : "generators",
  9 : "geometry",
  10 : "heterogeneous",
  11 : "hlt",
  12 : "l1",
  13 : "ml",
  14 : "operations",
  15 : "pdmv",
  16 : "reconstruction",
  17 : "simulation",
  18 : "tests",
  19 : "upgrade",
  20 : "visualization",
  21 : "xpog"
};
